<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/iris2.png?raw=true" width=800 align="left"/>

# 실습 내용

- Iris 데이터로 모델링합니다.
- Logistic Regression 알고리즘으로 모델링합니다.


# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%config InlineBackend.figure_format='retina'

In [2]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/iris.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [3]:
# 상위 몇 개 행 확인
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
# 기초통계량 확인
data.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
# 범주값 개수 확인
data['Species'].value_counts()

versicolor    50
setosa        50
virginica     50
Name: Species, dtype: int64

In [6]:
# 상관관계 확인
data.corr()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.000000    -0.117570      0.871754     0.817941
Sepal.Width      -0.117570     1.000000     -0.428440    -0.366126
Petal.Length      0.871754    -0.428440      1.000000     0.962865
Petal.Width       0.817941    -0.366126      0.962865     1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) x, y 분리**

- target 변수를 명확히 지정합니다.
- target을 제외한 변수를 x 데이터프레임으로 선언합니다.
- y 데이터프레임은 target 변수만을 가집니다.

In [7]:
# target 확인
target = 'Species'

# 데이터 분리
x = data.drop(target, axis=1)
y = data[target]

**2) 학습용, 평가용 데이터 분리**

- 학습용, 평가용 데이터를 적절한 비율로 분리합니다.
- 반복 실행 시 동일한 결과를 얻기 위해 random_state 옵션을 지정합니다.

In [8]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2022)  

# 4.모델링

- 본격적으로 모델을 선언하고 학습하고 평가하는 과정을 진행합니다.

In [9]:
# 1단계: 불러오기
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report


In [15]:
# 2단계: 선언하기
model = LogisticRegression(max_iter=1000)

In [16]:
# 3단계: 학습하기
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [17]:
# 4단계: 예측하기
y_pred = model.predict(x_test)

In [18]:
# 5단계 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[14  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.94      1.00      0.97        15
   virginica       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [20]:
y_pred[:10]

array(['virginica', 'virginica', 'setosa', 'virginica', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor'],
      dtype=object)

In [29]:
# [sentosa일 확률,virsicolor일 확률,virginica일 확률]
model.predict_proba(x_test)[:10]

array([[3.78219070e-05, 6.10460525e-02, 9.38916126e-01],
       [4.15931640e-07, 1.40231289e-02, 9.85976455e-01],
       [9.56803432e-01, 4.31960672e-02, 5.01282058e-07],
       [1.92587252e-04, 1.76050526e-01, 8.23756886e-01],
       [9.75213657e-01, 2.47861801e-02, 1.62532026e-07],
       [9.75405698e-01, 2.45940514e-02, 2.50199650e-07],
       [8.23364555e-02, 9.11081167e-01, 6.58237773e-03],
       [4.29477104e-02, 9.33899036e-01, 2.31532539e-02],
       [9.75404181e-01, 2.45956969e-02, 1.21957532e-07],
       [2.44125961e-02, 9.48653139e-01, 2.69342649e-02]])

In [22]:
y_test[:10]

128     virginica
105     virginica
30         setosa
137     virginica
17         setosa
8          setosa
79     versicolor
80     versicolor
0          setosa
67     versicolor
Name: Species, dtype: object

In [34]:
result = pd.DataFrame(y_test)
result['pred'] = y_pred
result.rename(columns={'Species':'test'},inplace=True)
result['result'] = 'O'
result.loc[result['test']!=result['pred'],'result'] = 'X'
result

test        pred result
128   virginica   virginica      O
105   virginica   virginica      O
30       setosa      setosa      O
137   virginica   virginica      O
17       setosa      setosa      O
8        setosa      setosa      O
79   versicolor  versicolor      O
80   versicolor  versicolor      O
0        setosa      setosa      O
67   versicolor  versicolor      O
91   versicolor  versicolor      O
131   virginica   virginica      O
58   versicolor  versicolor      O
100   virginica   virginica      O
118   virginica   virginica      O
5        setosa      setosa      O
95   versicolor  versicolor      O
129   virginica   virginica      O
103   virginica   virginica      O
92   versicolor  versicolor      O
36       setosa      setosa      O
43       setosa      setosa      O
111   virginica   virginica      O
39       setosa      setosa      O
115   virginica   virginica      O
133   virginica  versicolor      X
121   virginica   virginica      O
20       setosa      setosa      O
68   versicolor  versicolor      O
146   virginica   virginica      O
38       setosa      setosa      O
82   versicolor  versicolor      O
89   versicolor  versicolor      O
1        setosa      setosa      O
74   versicolor  versicolor      O
6        setosa      setosa      O
34       setosa      setosa      O
69   versicolor  versicolor      O
44       setosa      setosa      O
59   versicolor  versicolor      O
147   virginica   virginica      O
66   versicolor  versicolor      O
57   versicolor  versicolor      O
107   virginica   virginica      O
139   virginica   virginica      O

In [37]:
data.iloc[133]

Sepal.Length          6.3
Sepal.Width           2.8
Petal.Length          5.1
Petal.Width           1.5
Species         virginica
Name: 133, dtype: object